INSERT INTO dota2.heroes (common_name) VALUES ('Alchemist');
INSERT INTO dota2.heroes (common_name) VALUES ('Ancient Apparition');
INSERT INTO dota2.heroes (common_name) VALUES ('Antimage');
INSERT INTO dota2.heroes (common_name) VALUES ('Axe');
INSERT INTO dota2.heroes (common_name) VALUES ('Bane');
INSERT INTO dota2.heroes (common_name) VALUES ('Batrider');
INSERT INTO dota2.heroes (common_name) VALUES ('Beastmaster');
INSERT INTO dota2.heroes (common_name) VALUES ('Bloodseeker');
INSERT INTO dota2.heroes (common_name) VALUES ('Bounty Hunter');
INSERT INTO dota2.heroes (common_name) VALUES ('Brewmaster');
INSERT INTO dota2.heroes (common_name) VALUES ('Broodmother');
INSERT INTO dota2.heroes (common_name) VALUES ('Centaur');
INSERT INTO dota2.heroes (common_name) VALUES ('Chaos Knight');
INSERT INTO dota2.heroes (common_name) VALUES ('Chen');
INSERT INTO dota2.heroes (common_name) VALUES ('Clinkz');
INSERT INTO dota2.heroes (common_name) VALUES ('Crystal Maiden');
INSERT INTO dota2.heroes (common_name) VALUES ('Dark Seer');
INSERT INTO dota2.heroes (common_name) VALUES ('Dazzle');
INSERT INTO dota2.heroes (common_name) VALUES ('Death Prophet');
INSERT INTO dota2.heroes (common_name) VALUES ('Disruptor');
INSERT INTO dota2.heroes (common_name) VALUES ('Doom Bringer');
INSERT INTO dota2.heroes (common_name) VALUES ('Dragon Knight');
INSERT INTO dota2.heroes (common_name) VALUES ('Drow Ranger');
INSERT INTO dota2.heroes (common_name) VALUES ('Earthshaker');
INSERT INTO dota2.heroes (common_name) VALUES ('Enchantress');
INSERT INTO dota2.heroes (common_name) VALUES ('Enigma');
INSERT INTO dota2.heroes (common_name) VALUES ('Faceless Void');
INSERT INTO dota2.heroes (common_name) VALUES ('Nature\''s Prophet');
INSERT INTO dota2.heroes (common_name) VALUES ('Gyrocopter');
INSERT INTO dota2.heroes (common_name) VALUES ('Huskar');
INSERT INTO dota2.heroes (common_name) VALUES ('Invoker');
INSERT INTO dota2.heroes (common_name) VALUES ('Jakiro');
INSERT INTO dota2.heroes (common_name) VALUES ('Juggernaut');
INSERT INTO dota2.heroes (common_name) VALUES ('Keeper of the Light');
INSERT INTO dota2.heroes (common_name) VALUES ('Kunkka');
INSERT INTO dota2.heroes (common_name) VALUES ('Leshrac');
INSERT INTO dota2.heroes (common_name) VALUES ('Lich');
INSERT INTO dota2.heroes (common_name) VALUES ('Lifestealer');
INSERT INTO dota2.heroes (common_name) VALUES ('Lina');
INSERT INTO dota2.heroes (common_name) VALUES ('Lion');
INSERT INTO dota2.heroes (common_name) VALUES ('Lone Druid');
INSERT INTO dota2.heroes (common_name) VALUES ('Luna');
INSERT INTO dota2.heroes (common_name) VALUES ('Lycan');
INSERT INTO dota2.heroes (common_name) VALUES ('Magnus');
INSERT INTO dota2.heroes (common_name) VALUES ('Meepo');
INSERT INTO dota2.heroes (common_name) VALUES ('Mirana');
INSERT INTO dota2.heroes (common_name) VALUES ('Morphling');
INSERT INTO dota2.heroes (common_name) VALUES ('Naga Siren');
INSERT INTO dota2.heroes (common_name) VALUES ('Necrolyte');
INSERT INTO dota2.heroes (common_name) VALUES ('Shadow Fiend');
INSERT INTO dota2.heroes (common_name) VALUES ('Night Stalker');
INSERT INTO dota2.heroes (common_name) VALUES ('Nyx Assassin');
INSERT INTO dota2.heroes (common_name) VALUES ('Outworld Destroyer');
INSERT INTO dota2.heroes (common_name) VALUES ('Ogre Magi');
INSERT INTO dota2.heroes (common_name) VALUES ('Omniknight');
INSERT INTO dota2.heroes (common_name) VALUES ('Phantom Assassin');
INSERT INTO dota2.heroes (common_name) VALUES ('Phantom Lancer');
INSERT INTO dota2.heroes (common_name) VALUES ('Puck');
INSERT INTO dota2.heroes (common_name) VALUES ('Pudge');
INSERT INTO dota2.heroes (common_name) VALUES ('Pugna');
INSERT INTO dota2.heroes (common_name) VALUES ('Queen of Pain');
INSERT INTO dota2.heroes (common_name) VALUES ('Clockwerk');
INSERT INTO dota2.heroes (common_name) VALUES ('Razor');
INSERT INTO dota2.heroes (common_name) VALUES ('Riki');
INSERT INTO dota2.heroes (common_name) VALUES ('Rubick');
INSERT INTO dota2.heroes (common_name) VALUES ('Sand King');
INSERT INTO dota2.heroes (common_name) VALUES ('Shadow Demon');
INSERT INTO dota2.heroes (common_name) VALUES ('Silencer');
INSERT INTO dota2.heroes (common_name) VALUES ('Shadow Shaman');
INSERT INTO dota2.heroes (common_name) VALUES ('Skeleton King');
INSERT INTO dota2.heroes (common_name) VALUES ('Slardar');
INSERT INTO dota2.heroes (common_name) VALUES ('Slark');
INSERT INTO dota2.heroes (common_name) VALUES ('Spectre');
INSERT INTO dota2.heroes (common_name) VALUES ('Sniper');
INSERT INTO dota2.heroes (common_name) VALUES ('Spirit Breaker');
INSERT INTO dota2.heroes (common_name) VALUES ('Storm Spirit');
INSERT INTO dota2.heroes (common_name) VALUES ('Sven');
INSERT INTO dota2.heroes (common_name) VALUES ('Templar Assassin');
INSERT INTO dota2.heroes (common_name) VALUES ('Tidehunter');
INSERT INTO dota2.heroes (common_name) VALUES ('Tinker');
INSERT INTO dota2.heroes (common_name) VALUES ('Treant');
INSERT INTO dota2.heroes (common_name) VALUES ('Tiny');
INSERT INTO dota2.heroes (common_name) VALUES ('Undying');
INSERT INTO dota2.heroes (common_name) VALUES ('Ursa');
INSERT INTO dota2.heroes (common_name) VALUES ('Vengeful Spirit');
INSERT INTO dota2.heroes (common_name) VALUES ('Venomancer');
INSERT INTO dota2.heroes (common_name) VALUES ('Viper');
INSERT INTO dota2.heroes (common_name) VALUES ('Visage');
INSERT INTO dota2.heroes (common_name) VALUES ('Warlock');
INSERT INTO dota2.heroes (common_name) VALUES ('Weaver');
INSERT INTO dota2.heroes (common_name) VALUES ('Windrunner');
INSERT INTO dota2.heroes (common_name) VALUES ('Wisp');
INSERT INTO dota2.heroes (common_name) VALUES ('Witch Doctor');
INSERT INTO dota2.heroes (common_name) VALUES ('Zeus');