DROP TABLE dota2.heroes;
CREATE TABLE dota2.heroes(id serial, hero_name varchar(50), common_name varchar(50), hero_img varchar(300));
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('alchemist', 'alchemist_hphover','Alchemist');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('ancient_apparition', 'ancient_apparition_hphover','Ancient Apparition');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('antimage','antimage_hphover','Antimage');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('axe','axe_hphover','Axe');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('bane','bane_hphover','Bane');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('batrider','batrider_hphover','Batrider');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('beastmaster','beastmaster_hphover','Beastmaster');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('bloodseeker','bloodseeker_hphover','Bloodseeker');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('bounty_hunter','bounty_hunter_hphover','Bounty Hunter');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('brewmaster','brewmaster_hphover','Brewmaster');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('broodmother','broodmother_hphover','Broodmother');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('centaur','centaur_hphover','Centaur');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('chaos_knight','chaos_knight_hphover','Chaos Knight');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('chen','chen_hphover','Chen');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('clinkz','clinkz_hphover','Clinkz');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('crystal_maiden','crystal_maiden_hphover','Crystal Maiden');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('dark_seer','dark_seer_hphover','Dark Seer');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('dazzle','dazzle_hphover','Dazzle');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('death_prophet','death_prophet_hphover','Death Prophet');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('disruptor','disruptor_hphover','Disruptor');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('doom_bringer','doom_bringer_hphover','Doom Bringer');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('dragon_knight','dragon_knight_hphover','Dragon Knight');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('drow_ranger','drow_ranger_hphover','Drow Ranger');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('earthshaker','earthshaker_hphover','Earthshaker');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('enchantress','enchantress_hphover','Enchantress');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('enigma','enigma_hphover','Enigma');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('faceless_void','faceless_void_hphover','Faceless Void');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('furion','furion_hphover','Natures Prophet');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('gyrocopter','gyrocopter_hphover','Gyrocopter');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('huskar','huskar_hphover','Huskar');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('invoker','invoker_hphover','Invoker');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('jakiro','jakiro_hphover','Jakiro');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('juggernaut','juggernaut_hphover','Juggernaut');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('keeper_of_the_light','keeper_of_the_light_hphover','Keeper of the Light');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('kunkka','kunkka_hphover','Kunkka');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('leshrac','leshrac_hphover','Leshrac');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('lich','lich_hphover','Lich');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('life_stealer','life_stealer_hphover','Lifestealer');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('lina','lina_hphover','Lina');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('lion','lion_hphover','Lion');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('lone_druid','lone_druid_hphover','Lone Druid');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('luna','luna_hphover','Luna');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('lycan','lycan_hphover','Lycan');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('magnataur','magnataur_hphover','Magnus');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('meepo','meepo_hphover','Meepo');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('mirana','mirana_hphover','Mirana');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('morphling','morphling_hphover','Morphling');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('naga_siren','naga_siren_hphover','Naga Siren');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('necrolyte','necrolyte_hphover','Necrolyte');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('nevermore','nevermore_hphover','Shadow Fiend');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('night_stalker','night_stalker_hphover','Night Stalker');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('nyx_assassin','nyx_assassin_hphover','Nyx Assassin');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('obsidian_destroyer','obsidian_destroyer_hphover','Outworld Destroyer');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('ogre_magi','ogre_magi_hphover','Ogre Magi');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('omniknight','omniknight_hphover','Omniknight');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('phantom_assassin','phantom_assassin_hphover','Phantom Assassin');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('phantom_lancer','phantom_lancer_hphover','Phantom Lancer');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('puck','puck_hphover','Puck');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('pudge','pudge_hphover','Pudge');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('pugna','pugna_hphover','Pugna');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('queenofpain','queenofpain_hphover','Queen of Pain');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('rattletrap','rattletrap_hphover','Clockwerk');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('razor','razor_hphover','Razor');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('riki','riki_hphover','Riki');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('rubick','rubick_hphover','Rubick');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('sand_king','sand_king_hphover','Sand King');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('shadow_demon','shadow_demon_hphover','Shadow Demon');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('silencer','silencer_hphover','Silencer');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('shadow_shaman','shadow_shaman_hphover','Shadow Shaman');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('skeleton_king','skeleton_king_hphover','Skeleton King');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('slardar','slardar_hphover','Slardar');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('slark','slark_hphover','Slark');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('spectre','spectre_hphover','Spectre');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('sniper','sniper_hphover','Sniper');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('spirit_breaker','spirit_breaker_hphover','Spirit Breaker');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('storm_spirit','storm_spirit_hphover','Storm Spirit');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('sven','sven_hphover','Sven');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('templar_assassin','templar_assassin_hphover','Templar Assassin');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('tidehunter','tidehunter_hphover','Tidehunter');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('tinker','tinker_hphover','Tinker');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('treant','treant_hphover','Treant');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('tiny','tiny_hphover','Tiny');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('undying','undying_hphover','Undying');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('ursa','ursa_hphover','Ursa');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('vengefulspirit','vengefulspirit_hphover','Vengeful Spirit');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('venomancer','venomancer_hphover','Venomancer');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('viper','viper_hphover','Viper');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('visage','visage_hphover','Visage');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('warlock','warlock_hphover','Warlock');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('weaver','weaver_hphover','Weaver');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('windrunner','windrunner_hphover','Windrunner');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('wisp','wisp_hphover','Wisp');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('witch_doctor','witch_doctor_hphover','Witch Doctor');
INSERT INTO dota2.heroes (hero_name, hero_img,common_name) VALUES ('zuus','zuus_hphover','Zeus');
